pipeline {
    agent any

    stages {
        stage('Build docker image') {
            steps {
                script {
                    sh 'docker build -t jenkins-image .'
                }
            }
        }

        stage('Run docker container') {
            steps {
                script {
                    // Run Jenkins container
                    def jenkinsContainerId = sh(script: 'docker run -d -p 8080:8080 -p 50000:50000 jenkins-image', returnStatus: true).trim()
                    
                    sh "docker exec ${jenkinsContainerId} /bin/bash -c 'while [[ ! -f /var/jenkins_home/secrets/initialAdminPassword ]]; do sleep 1; done'"
                }
            }
        }

        stage('Clone repository and build packages') {
            steps {
                script {
                    git url: 'https://github.com/ShadowDrake21/Krapyvianskyi_OS'
                    dir('Krapyvianskyi_OS/rpm') {
                        sh 'rpmbuild -ba numOfFiles.spec'
                    }
                }
            }
        }

        stage('Install RPM and execute script') {
            steps {
                script {
                    // Install RPM and execute script
                    sh 'docker exec ${jenkinsContainerId} /bin/bash -c "yum install -y /root/rpmbuild/RPMS/x86_64/num-of-files-1.0-1.x86_64.rpm"'
                    sh 'docker exec ${jenkinsContainerId} /bin/bash -c "/usr/bin/num-of-files.sh"'
                }
            }
        }
    }
}
