name: Build Deb Package

on:
  push:
    branches:
      - main
    paths:
      - 'debian/**/*'
      - '**.sh'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v2

      - name: Install DEB build tools
        run: |
          sudo apt-get install -y debhelper dh-make

      - name: Build DEB
        run: |
          cd debian
          dh_make -s -y
          dpkg-buildpackage -us -uc

      - name: Upload DEB Packages
        uses: actions/upload-artifact@v2
        with:
          name: deb-packages
          path: debian/*.deb
 