name: Build DEB Package

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'debian/**'
      - '*.sh'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper dh-make devscripts

      - name: Download source code
        run: |
          wget https://github.com/ShadowDrake21/Krapyvianskyi_OS/archive/main.zip
          unzip main.zip
          mv Krapyvianskyi_OS-main/debian/* debian/
          rm -r Krapyvianskyi_OS-main

      - name: Build DEB
        run: debuild -us -uc

      - name: Upload DEB
        uses: actions/upload-artifact@v2
        with:
          name: deb-package
          path: |
            ../num-of-files_1.0-1_all.deb
            ../num-of-files_1.0-1.debian.tar.xz
            ../num-of-files_1.0-1.dsc
            ../num-of-files_1.0.orig.tar.xz