name: Build RPM Package

on:
  push:
    branches:
      - main
    paths:
      - 'rpm/**.spec'
      - '**.sh'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: centos:7  # Use CentOS 7

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install RPM build tools
        run: |
          yum install -y rpm-build rpmdevtools wget unzip
          rpmdev-setuptree

      - name: Build RPM
        run: |
          cp rpm/numOfFiles.spec ~/rpmbuild/SPECS/
          cd ~/rpmbuild/SOURCES/
          wget https://github.com/ShadowDrake21/Krapyvianskyi_OS/archive/main.zip
          unzip main.zip
          mv Krapyvianskyi_OS-main/* .
          rmdir Krapyvianskyi_OS-main
          cd ~/rpmbuild/
          rpmbuild -bs --define "dist .generic" SPECS/numOfFiles.spec
          rpmbuild --rebuild SRPMS/num-of-files-1.0-1.src.rpm

      - name: Upload RPM
        uses: actions/upload-artifact@v2
        with: 
          name: rpm-package
          path: |
            ~/rpmbuild/RPMS/**/*.rpm
            ~/rpmbuild/SRPMS/**/*.src.rpm  